export { default as LoginBackground } from './login-background.jpg'
export { default as USFlag } from './us-flag.png'
export { default as VIFlag } from './vi-flag.png'
export { default as OrderSuccess } from './order-success.svg'
export { default as Logo } from './logo.png'
export { default as LogoWhite } from './logo-white.png'
export { default as TabLogo } from './tab-logo.png'
export { default as PopupLogo } from './popup-logo.png'
export { default as LandingPageBackground } from './landing-page-background.webp'
export { default as LandingPageBackgroundMobile } from './landing-page-background-mobile.jpg'
export { default as HomelandLogo } from './homeland-logo.png'
export { default as TabHomelandLogo } from './tab-homeland-logo.png'
export { default as ErrorIllustration } from './error-page-logo.svg'
export { default as NotFoundIllustration } from './404-page-logo.svg'
export { default as FeaturedServices1 } from './featured-services-1.webp'
export { default as FeaturedServices2 } from './featured-services-2.webp'
export { default as FeaturedServices3 } from './featured_service_3.webp'
export { default as FeaturedServices4 } from './featured_service_4.webp'
export { default as LogoIcon } from './logo-icon.png'
export { default as NewsArticle11 } from './news_article_1_1.webp'
export { default as NewsArticle12 } from './news_article_1_2.webp'
export { default as NewsArticle13 } from './news_article_1_3.webp'
export { default as NewsArticle21 } from './news_article_2_1.webp'
export { default as NewsArticle22 } from './news_article_2_2.webp'
export { default as NewsArticle23 } from './news_article_2_3.webp'
export { default as NewsArticle31 } from './news_article_3_1.webp'
export { default as NewsArticle32 } from './news_article_3_2.webp'
export { default as NewsArticle33 } from './news_article_3_3.webp'
export { default as NewsArticle34 } from './news_article_3_4.webp'
export {default as HighlightMenu2} from './highlight_menu_2.webp'
export {default as HighlightMenu3} from './highlight_menu_3.webp'
export {default as HighlightMenu4} from './highlight_menu_4.webp'
export {default as HighlightMenu5} from './highlight_menu_5.webp'
export {default as ProductImage} from './default-product-image.png'