export const ROUTE = {
  HOME: '/',
  PERSONAL_ACCOUNT: '/personal-account',
  ADMIN: '/admin',
  LOGIN: '/auth/login',
  REGISTER: '/auth/register',
  REGISTER_OTP: '/auth/register/otp',
  REGISTER_PROFILE: '/auth/register/profile',
  FORGOT_PASSWORD: '/auth/forgot-password',
  FORGOT_PASSWORD_BY_EMAIL: '/auth/forgot-password/email',
  FORGOT_PASSWORD_BY_PHONE: '/auth/forgot-password/phone',
  RESET_PASSWORD: '/reset-password',
  ORDER_SUCCESS: '/order-success',
  CLIENT_ORDER_SUCCESS: '/client/order-success',
  CLIENT_GIFT_CARD_SUCCESS: '/client/gift-card/confirmation',
  SYSTEM_GIFT_CARD_SUCCESS: '/system/card/catalog/confirmation',
  VERIFY_EMAIL: '/verify-email', // Make sure this matches exactly with your URL path
  FORBIDDEN: '/403',

  // System Routes
  OVERVIEW: '/system/overview',
  OVERVIEW_DETAIL: '/system/overview/detail',
  STAFF_BRANCH: '/system/branch',
  STAFF_BRANCH_AND_SYSTEM_MANAGEMENT: '/system/branch-and-system-management',
  STAFF_BRANCH_DETAIL: '/system/branch-and-system-management/branch/:slug',
  STAFF_PROFILE: '/system/profile',
  STAFF_MENU: '/system/menu',
  STAFF_CUSTOMER_DISPLAY: '/system/customer-display',
  STAFF_CHECKOUT_ORDER: '/checkout-order',
  STAFF_ORDER_PAYMENT: '/system/payment',
  STAFF_DELIVERY_MANAGEMENT: '/system/delivery-management',
  STAFF_CHEF_ORDER: '/system/chef-order',
  STAFF_ORDER_MANAGEMENT: '/system/order-management',
  STAFF_CARD_ORDER_MANAGEMENT: '/system/card-order-management',
  // STAFF_UPDATE_ORDER: '/system/update-order',
  STAFF_ORDER_PREPARATION: '/order-preparation',
  STAFF_TABLE_MANAGEMENT: '/system/table',
  STAFF_PRODUCT_MANAGEMENT: '/system/product',
  STAFF_MENU_AND_PRODUCT_MANAGEMENT: '/system/menu-and-product-management',
  // STAFF_DELIVERY_MANAGEMENT: '/delivery-management',
  STAFF_WALLET_MANAGEMENT: '/system/wallet-management',
  STAFF_LOG_MANAGEMENT: '/system/log',
  STAFF_USER_MANAGEMENT: '/system/staff',
  STAFF_CUSTOMER_MANAGEMENT: '/system/customers',
  STAFF_CUSTOMER_AND_MARKETING_MANAGEMENT: '/system/customer-and-marketing-management',
  STAFF_CUSTOMER_AND_MARKETING_VOUCHER_GROUP: '/system/customer-and-marketing-management/voucher-group',
  STAFF_CUSTOMER_AND_MARKETING_CUSTOMER_GROUP: '/system/customer-and-marketing-management/customer-group',
  STAFF_CUSTOMER_GROUP_MANAGEMENT: '/system/customer-group-management',
  STAFF_ROLE_MANAGEMENT: '/system/role',
  STAFF_BANK_CONFIG: '/system/bank-config',
  STAFF_STATIC_PAGE: '/system/static-page',
  STAFF_VOUCHER_GROUP: '/system/voucher-group',
  STAFF_PROMOTION: '/system/promotion',
  STAFF_CHEF_AREA_MANAGEMENT: '/system/area',
  STAFF_INVOICE_AREA_MANAGEMENT: '/system/invoice-area',
  STAFF_BANNER: '/system/banner',
  STAFF_CONFIG: '/system/config',
  STAFF_SYSTEM_MANAGEMENT: '/system/system-management',
  STAFF_GIFT_CARD: '/system/gift-card',
  STAFF_GIFT_CARD_MENU: '/system/card/catalog',
  STAFF_GIFT_CARD_FEATURE_FLAG: '/system/feature-lock-management',
  STAFF_SYSTEM_LOCK_MANAGEMENT: '/system/system-lock-management',
  STAFF_GIFT_CARD_CHECKOUT: '/system/card/catalog/checkout',
  STAFF_GIFT_CARD_CHECKOUT_WITH_SLUG: '/system/card/catalog/checkout/:slug',
  STAFF_COIN_POLICY: '/system/coin-policy',
  STAFF_CAMPAIGN: '/system/customer-and-marketing-management/campaign',
  STAFF_CAMPAIGN_CREATE: '/system/customer-and-marketing-management/campaign/create',
  STAFF_CAMPAIGN_DETAIL: '/system/customer-and-marketing-management/campaign/:slug',

  //Client Routes
  CLIENT_HOME: '/',
  CLIENT_BOOKING: '/booking',
  CLIENT_NEWS: '/news',
  CLIENT_NEWS_DETAIL: '/news/:slug',
  CLIENT_MENU: '/menu',
  CLIENT_MENU_ITEM: '/menu-item',
  CLIENT_CART: '/cart',
  CLIENT_CHECKOUT_ORDER: '/checkout-order',
  CLIENT_PAYMENT: '/payment',
  CLIENT_ORDER_HISTORY: '/history',
  CLIENT_UPDATE_ORDER: '/update-order',
  CLIENT_PROFILE: '/profile',
  CLIENT_PROFILE_INFO: '/profile/info',
  CLIENT_PROFILE_HISTORY: '/profile/history',
  CLIENT_PROFILE_LOYALTY_POINT: '/profile/loyalty-point',
  CLIENT_PROFILE_COIN: '/profile/coin',
  CLIENT_PROFILE_GIFT_CARD: '/profile/gift-card',
  CLIENT_ORDERS_PUBLIC: '/orders-public',
  CLIENT_GIFT_CARD: '/gift-card',
  CLIENT_GIFT_CARD_CHECKOUT: '/gift-card/checkout',
  CLIENT_GIFT_CARD_CHECKOUT_WITH_SLUG: '/gift-card/checkout/:slug',
  CLIENT_DOWNLOAD: '/download',
  // CLIENT_VOUCHER: '/voucher',

  // General Routes
  ABOUT: '/about',
  CONTACT: '/contact',
  HELP: '/help',
  POLICY: '/policy',
  ACCOUNT_DELETION: '/delete-account',
  SECURITY: '/security',
  DOCS: '/docs',
  ORDER_INSTRUCTIONS: '/order-instructions',
  PAYMENT_INSTRUCTIONS: '/payment-instructions',

  ADMIN_CONFIG: 'system/config',
  ADMIN_VOUCHER: 'system/voucher',
  ADMIN_PROMOTION: 'system/promotion',
  ADMIN_BANNER: 'system/banner',
}
