name: trend-ui-cloud

services:
  trend-ui:
    image: ghcr.io/homeslands/trend-ui:latest
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "5177"] # TCP check on port 5177
      interval: 10s # Increase interval between health checks
      timeout: 10s # Increase timeout for slower responses
      retries: 5
    restart: unless-stopped

networks:
  default:
    external: true
    name: scoobydoo
